{"timestamp":"2025-10-08T08:21:49.067785","level":"info","event":"DAG bundles loaded: dags-folder","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-10-08T08:21:49.069574","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/user_processing.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-10-08T08:21:49.362508","level":"info","event":"Executing: \n            CREATE TABLE IF NOT EXISTS users (\n            id INT PRIMARY KEY,\n            firstname VARCHAR NOT NULL,\n            lastname VARCHAR NOT NULL,\n            email VARCHAR NOT NULL,\n            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP\n        );\n        ","logger":"airflow.task.operators.airflow.providers.common.sql.operators.sql.SQLExecuteQueryOperator"}
{"timestamp":"2025-10-08T08:21:49.367394","level":"info","event":"Secrets backends loaded for worker","count":1,"backend_classes":["EnvironmentVariablesBackend"],"logger":"supervisor"}
{"timestamp":"2025-10-08T08:21:49.367697","level":"error","event":"Unable to retrieve connection from secrets backend (EnvironmentVariablesBackend). Checking subsequent secrets backend.","logger":"task","error_detail":[{"exc_type":"AttributeError","exc_value":"'NoneType' object has no attribute 'upper'","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/context.py","lineno":129,"name":"_get_connection"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/secrets/base_secrets.py","lineno":76,"name":"get_connection"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/secrets/environment_variables.py","lineno":34,"name":"get_conn_value"}]}]}
{"timestamp":"2025-10-08T08:21:49.368666","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"ValidationError","exc_value":"1 validation error for GetConnection\nconn_id\n  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]\n    For further information visit https://errors.pydantic.dev/2.11/v/string_type","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":825,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1088,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":408,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py","lineno":302,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py","lineno":196,"name":"get_db_hook"},{"filename":"/usr/local/lib/python3.12/functools.py","lineno":998,"name":"__get__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py","lineno":172,"name":"_hook"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py","lineno":164,"name":"get_hook"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py","lineno":64,"name":"get_connection"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py","lineno":472,"name":"get_connection_from_secrets"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/definitions/connection.py","lineno":142,"name":"get"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/context.py","lineno":157,"name":"_get_connection"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/pydantic/main.py","lineno":253,"name":"__init__"}]}]}
